name: Push master

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/backend-tests-on-docker.yml
    secrets: inherit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v5.0.0
        with:
          event-type: update
          images: |
            inspirehep/next@{{ needs.test.outputs.tag }}
            inspirehep/next-assets@{{ needs.test.outputs.tag }}
            inspirehep/next-scrapyd@{{ needs.test.outputs.tag }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}