name: Push master

on:
  push:
    branches: [master]
  release:
    types: [released]

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/backend-tests-on-docker.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v5.6.0
        with:
          event-type: ${{ needs.test.outputs.type }}
          images: |
            inspirehep/next@${{ needs.test.outputs.tag }}
            inspirehep/next-assets@${{ needs.test.outputs.tag }}
            inspirehep/next-scrapyd@${{ needs.test.outputs.tag }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

